"""initial database

Revision ID: 01961428e8db
Revises: 
Create Date: 2025-10-07 11:38:51.922969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01961428e8db'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_arquivo', sa.String(), nullable=True),
    sa.Column('resultado', sa.JSON(), nullable=True),
    sa.Column('clausulas_problematicas', sa.JSON(), nullable=True),
    sa.Column('sugestoes', sa.JSON(), nullable=True),
    sa.Column('data_analise', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analises_id'), 'analises', ['id'], unique=False)
    op.create_index(op.f('ix_analises_nome_arquivo'), 'analises', ['nome_arquivo'], unique=False)
    op.create_table('analises_contratos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_arquivo', sa.String(), nullable=True),
    sa.Column('score_risco', sa.Integer(), nullable=True),
    sa.Column('resumo_riscos', sa.JSON(), nullable=True),
    sa.Column('analise_completa_ia', sa.String(), nullable=True),
    sa.Column('data_analise', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analises_contratos_id'), 'analises_contratos', ['id'], unique=False)
    op.create_index(op.f('ix_analises_contratos_nome_arquivo'), 'analises_contratos', ['nome_arquivo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analises_contratos_nome_arquivo'), table_name='analises_contratos')
    op.drop_index(op.f('ix_analises_contratos_id'), table_name='analises_contratos')
    op.drop_table('analises_contratos')
    op.drop_index(op.f('ix_analises_nome_arquivo'), table_name='analises')
    op.drop_index(op.f('ix_analises_id'), table_name='analises')
    op.drop_table('analises')
    # ### end Alembic commands ###
